### ISSUE TITLE
BUG: I can't download the models

### ISSUE THREAD

**Issue by Daniloper** [QIMP-Team/MOOSE#95] opened 2024-01-28 16:09 UTC
Hi everyone!

**Describe the bug**
I can not use a model, that I haven't used before, because the model can not be downloaded.
For example: moosez -d /path/ -m clin_ct_lungs

**To Reproduce**
1. Try to use a model that you haven't used before

**Screenshots**
![Screenshot from 2024-01-28 17-03-18](https://github.com/QIMP-Team/MOOSE/assets/57219733/894f6d34-0802-40d7-b94c-e8258a49268d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by LalithShiyam** [comment] 2024-01-28 16:16
Hi @Daniloper,
Could you please let me know the version of moose you are using. We have migrated from ibm to aws. So the links from old versions will not work. Check if the version is the latest. And then reinstall it in a fresh environment. Ideally it should work. Kindly let me know.
Cheers,
Lalith

**Comment by Daniloper** [comment] 2024-01-28 16:45
Hi Lalith,
I am using v2.0.0. I installed it in December and the download was working back then.

**Comment by LalithShiyam** [comment] 2024-01-28 16:52
Hi there, I would be needing the exact version of moose. You are talking about the "major release". We are at 2.3.9. 

You can check your actual version by typing: 

`pip show moosez`

**Comment by Daniloper** [comment] 2024-01-28 16:58
Yes I am using v2.3.4
I am going to try to upgrade it.

Thank you!

**Comment by LalithShiyam** [comment] 2024-01-28 17:01
Great please keep me posted if it works out.

**Comment by LalithShiyam** [comment] 2024-01-29 08:54
Hi @Daniloper, Is this solved or are you still having troubles?
Kindly let me know.
Cheers,
Lalith

**Comment by LalithShiyam** [comment] 2024-01-29 15:18
Could you elaborate more on the MPs check please. I am happy to fix it in the main branch.

**Comment by Daniloper** [comment] 2024-01-29 15:57
I get the following error:

![error](https://github.com/QIMP-Team/MOOSE/assets/57219733/54518233-17a5-46ff-a781-1e3842d44810)

**Comment by Keyn34** [comment] 2024-01-29 16:07
Hey @Daniloper, what is your NVIDIA driver version? According to the posted error, it seems to be too old.

**Comment by Daniloper** [comment] 2024-01-29 16:17
I have no GPU in that maschine. It is expected to run on CPU. But before the running could start, the MPS error occures.

**Comment by mprires** [comment] 2024-01-29 17:15
Hi, @Daniloper! I was able to reproduce your error and found a fix. Should be online now, test it and let us know :)

**Comment by LalithShiyam** [comment] 2024-01-29 20:20
In 2.4.0 - it's fixed!

**Comment by LalithShiyam** [comment] 2024-01-30 07:52
Hi @Daniloper kindly let us know if the error goes away from moosez 2.4.0. So that we can close the issue :)! Thanks again for pointing us towards the bug. Much appreciated!

**Comment by Daniloper** [comment] 2024-01-30 10:46
Hi @LalithShiyam,
I have tried the v2.4.0. It is working. Everything is fine now. Thank you!

**Closed** 2024-01-30 10:54 UTC
